### ISSUE TITLE
There is a huge issue...

### ISSUE THREAD

**Issue by NazmusSayad** [TasnimulHasan007/superchat#1]
Please watch this pinture

![image](https://user-images.githubusercontent.com/87106526/136963965-56f0caa0-7e72-42a7-a9b3-78641ab3c8ef.png)

I can't watch your files. Please fix it.

**Comment by TasnimulHasan007** [comment]
[image: image.png]
thik e to ache

**Comment by NazmusSayad** [comment]
Mane amar net slow . tai dekhacchilo na ...ekhon amar net thik kore daoo
